const profileIconIndex = [ 'user', //default option
        'ambulance',   'baseball ball',        'basketball ball', 'bath',
        'bed',         'beer',                 'bicycle',         'birthday cake',
        'bolt',        'bomb',                 'book',            'bowling ball', 
        'box',         'building',             'bullhorn',        'bus',
        'calculator',  'camera',               'car',             'chat',
        'clipboard',   'clock',                'coffee',          'compass',      
        'dollar sign', 'envelope',             'exclamation',     'fighter jet',  
        'fire',        'flag',                 'flask',           'football ball', 
        'frown',       'futbol',               'gamepad',         'gem',
        'gift',        'globe',                'golf ball',       'hand peace',   
        'hand spock',  'heart',                'hockey puck',     'home',
        'industry',    'key',                  'laptop',          'leaf',
        'lemon',       'lightbulb',            'magic',           'meh',
        'microchip',   'microphone',           'mobile',          'moon',
        'motorcycle',  'music',                'newspaper',       'paint brush',  
        'paw',         'pencil alternate',     'phone',           'plane',        
        'plug',        'power off',            'puzzle piece',    'question',     
        'recycle',     'road',                 'rocket',          'search',       
        'ship',        'shopping cart',        'shower',          'smile',        
        'snowflake',   'space shuttle',        'star',            'subway',       
        'suitcase',    'sun',                  'syringe',         'table tennis', 
        'tablet',      'tachometer alternate', 'taxi',            'thermometer',  
        'thumbs up',   'thumbtack',            'train',           'tree',
        'trophy',      'truck',                'tv',              'umbrella',     
        'university',  'utensils',             'volleyball ball', 'warehouse',
        'wrench'
];

export default profileIconIndex;